# Checks that the pkgdown site builds for a repository.
# this assumes pkgdown is already set up.
name: call-build-pkgdown
# on specifies the build triggers. See more info at https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
# this workflow runs on pushes to main
  push:
    branches: [main]
    # tags: ['*']
jobs:
  call-workflow:
    uses: nmfs-ost/ghactions4r/.github/workflows/build-pkgdown.yml@main
